### ISSUE TITLE
Language not switching to default language

### ISSUE THREAD

**Issue by danijelc77** [polylang/polylang#202]
## Prerequisites

- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.

I have an strange behavior on web sites with polylang installed. 

In cases where default language is set to "Hide URL language information for default language", web site is shown in English and can't switch to default language while it does switch to other languages. (switching work properly for all languages for which permalink is showing the language code).

Issue happens on homepage only and sub pages or tags  and categories are switching languages as expected. 

Only way to make it function properly is un-checking  "Hide URL language information for default language" 

It seems that when hiding default language information from the URL  Polylang doesn't recognize the language and defaults to English (i.e. in google search results clicking on link in default language  will open English language)

**Comment by marticos** [comment]
I have the same issue.

**Comment by Chouby** [comment]
I don't reproduce the issue. Please test on a vanilla WordPress install with Twenty Seventeen and Polylang only. And provide exact options to reproduce the issue.

**Comment by danijelc77** [comment]
On vanilla wordpress with no any data beside 3 main pages (3 languages each with home page only), issues not reproducing, will test further

**Comment by ShamanFromSiberia** [comment]
I have the same issue. To change laguage I have to clear brower's cache. The issue is being observed on many devices and browsers for a few months, now that's a problem because I'm getting more and more reports on this from many users. Any solution on this?

**Comment by mudassarchaudhry** [comment]
Go to Ploylang Setting and Detect browser language Module.
Hope the problem is solved.
More Solution http://mudassar.cloudaccess.host/

**Comment by 4faster** [comment]
I'm using Version 2.6.5 and it still not resolved

but I think it is more intuitive if we un-checking "Hide URL language information for default language".

**Comment by mudassarchaudhry** [comment]
okay, don't worry I solved your problem-free of cost. Email me: mudassarchaudhry5@gmail.com

**Comment by 4sh3** [comment]
Hello,

in my case the language is not switching to the secondary language (From English to Spanish).

Website: https://awakendreamers.co/

I have seen that the Spanish URL of the switcher is not working: https://awakendreamers.co/es/homepage-es/

However, if I go to this URL the language changes https://awakendreamers.co/es/ ¿Why? ¿what should I do to fix that issue?

Thank you

**Comment by rescuetoaster** [comment]
> Hello,
> 
> in my case the language is not switching to the secondary language (From English to Spanish).
> 
> Website: https://awakendreamers.co/
> 
> I have seen that the Spanish URL of the switcher is not working: https://awakendreamers.co/es/homepage-es/
> 
> However, if I go to this URL the language changes https://awakendreamers.co/es/ ¿Why? ¿what should I do to fix that issue?
> 
> Thank you

I have similar issue of language switching not working on primary domain that has more than 1 language translation on it.I have EST and RUS on the primary domain(site.ee) and se, fi on site.se and site.fi domains.
 The languages are handled by polylang url modifications function in settings.
Issue started when I enabled url modifications settings.

Can anyone shed some light in this ?

**Comment by marcelvrana** [comment]
its 2021 and i still dont have star to switch my default language? Why?

**Comment by Dark-Schneider-666** [comment]
As mentioned it only works well if uncheking “ Hide URL language information for default language” then clearing site cache from Wordpress dashboard.

So IMHO it would be better option if Polylang comes with this option disabled and instructions mentioning that if you have this trouble uncheck and clear site cache.

It should be related with redirection, seems it needs one for it to work, i.e. if I access my site without www it don’t work, if I access with www the domain redirects to without www and auto switch works. So I think that’s the reason when disabling the option works, because when you enter the site it redirects to mysite/en/ (i.e. with English as default), in other words it don’t disables redirection in any case.

**Comment by PLkolek** [comment]
@Chouby I believe I reproduced the issue. My site has "Detect browser language" on and "The language is set from content" on. Therefore, my front page is 
* https://example.com/ in English
* https://example.com/home-pl in Polish

If I enter the site and Polylang detects my language as Polish, I land on https://example.com/home-pl. Then, if I try to switch the language to English, the link leads to https://example.com/. Because it's the front page, Polylang detects the language again and brings me back to https://example.com/home-pl. If I disable "Detect browser language", everything works fine. It'd be nice if "Detect browser language" only worked on the first landing - once the user explicitly selects the language, detection should not kick in.

**Comment by jits04** [comment]
@PLkolek
same behaviour on my site. Good problem!
