### ISSUE TITLE
Term (Category/Tag) insertion removes list table columns

### ISSUE THREAD

**Issue by sybrew** [polylang/polylang#928]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Activate Polylang and any other plugin that works with Term insertion (Yoast SEO, The SEO Framework, etc.).
2. Insert a term.
3. Data gets overwritten

## Expected behavior and actual behavior

It's a grey because I ran `debugger`...

When I follow those steps, I see...
![image](https://user-images.githubusercontent.com/7662236/136924345-6252ceaa-5bc3-41e9-a0e6-78a31e4b8a82.png)

I was expecting...
![image](https://user-images.githubusercontent.com/7662236/136924326-14797e1f-9a6e-4e9c-990e-60890e333689.png)

This line is too greedy with its replacement: https://github.com/polylang/polylang/blob/3.1.2/js/src/term.js#L78

I don't think that line does anything useful since Polylang already correctly supplies the output via WordPress's List Table.

**Comment by Chouby** [comment]
Sorry, I thought I had already answered to this issue. Are you sure that the issue is with *any* plugin inserting a column? I have (re-)tested with the plugins I usually use for this feature (WooCommerce, Yoast SE0) and their columns are correctly filled when I insert a new term.

**Comment by sybrew** [comment]
Hi Chouby,

This issue on term-adding occurs with any column added _after_ the flag selection. Perhaps Yoast SEO has changed the order of columns recently, so they are no longer affected.

Yoast SEO is still affected, though, when you use post/page quick edit.

Please also test with other plugins, such as The SEO Framework, or even add a custom column after it so you can control the variables. Regardless, the code I advise removing doesn't seem to do anything useful (anymore).

**Comment by Chouby** [comment]
I tested again with Yoast SEO and its columns are displayed before the Polylang columns so if the order has an importance, I can't test it with this plugin.

I tested The SEO Framework too. Here I can reproduce the issue. However if I well understood the code, it is not related to the order of the columns but to the fact that the SEO column is added conditionnally. For what I have read, the filters are added based on the screen id (the general case for which we can see the column correctly displayed) and when handling some ajax response (add term / quick edit term). 

The filters are not added outside these contexts. That's in my opinion the source of the conflict with Polylang. Indeed, after the core ajax requests, Polylang fires a second ajax request because in some cases, the first action may impact translated terms, so we need to redraw the rows of all terms in the translation group. That's the purpose of the code you are pointing to. To build the response, the row is evaluated the [same way as WordPress](https://github.com/polylang/polylang/blob/3.1.2/admin/admin-filters-columns.php#L427) does, so it should honor all present filters. However, as this second ajax request is not known from The SEO Framework, the filters to add the columns are not added and thus the columns are not drawn.

My guess is that if the filters were always added (and not conditionnally), this would fix the issue.

**Comment by sybrew** [comment]
Please test the WordPress-native quick-edit functionality on the post-edit screen to see what I mean. It also affects Yoast SEO, as displayed in the screenshot attached in my previous reply. I'm not sure how a modification in The SEO Framework could help; this is not an issue in PHP, but it is at the JavaScript file I linked to in my first reply.

**Comment by Chouby** [comment]
Sorry, I was focused on the category screen. 

I reproduce the issue with the quick edit in the posts list table with the columns of Yoast SEO. For me, the same cause produces the same effects. Indeed, Yoast SEO adds the columns hooks in the class `WPSEO_Meta_Columns`. But this class is not instantiated for ajax requests other than `inline-save`. The test is made a first time [in the main class](https://github.com/Yoast/wordpress-seo/blob/17.7.1/wp-seo-main.php#L468-L470) and a second time in the [`WPSEO_Admin_Init`](https://github.com/Yoast/wordpress-seo/blob/17.7.1/admin/class-admin-init.php#L137) class.

**Comment by Chouby** [comment]
Closing as this was fixed on our side for the Yoast SEO integration. For any other plugin adding columns, the filters adding these columns should be always present even for ajax requests.

**Comment by sybrew** [comment]
You added a patch for Yoast SEO but didn't fix the underlying cause. This is still an issue for 55000 other plugins.

**Comment by sybrew** [comment]
The code you changed also breaks the quick edit functionality for third-party plugins. The fix I proposed (less interfering code is better) at https://github.com/polylang/polylang/pull/943#issuecomment-1292394037 still works.

**Comment by sybrew** [comment]
For anyone wishing to fix Polylang from breaking their plugin's quick-edit and column functionality, add this code to your plugin:
```php
namespace My_Plugin_Namespace; // change this!

\add_action( 'admin_enqueue_scripts', __NAMESPACE__ . '\\_defunct_badly_coded_polylang_script', 11 );
/**
 * Polylang breaks the admin interface quick-edit and terms-addition functionality.
 * This hack seeks to remove their broken code, letting WordPress take over
 * correctly once more with full forward and backward compatibility, as we proposed.
 *
 * @see https://github.com/polylang/polylang/issues/928
 */
function _defunct_badly_coded_polylang_script() {

	// Find last ajaxSuccess handler.
	// Since this code runs directly after Polylang, it should grab theirs.
	$remove_ajax_success = <<<'JS'
	jQuery( () => {
		const handler = jQuery._data( document, 'events' )?.ajaxSuccess?.pop().handler;
		handler && jQuery( document ).off( 'ajaxSuccess', handler );
	} );
JS;

	// Remove PLL term handler on ajaxSuccess. It is redundant, achieves nothing,
	// creates redundant secondary requests, and breaks all plugins but Yoast SEO.
	\wp_add_inline_script( 'pll_term', $remove_ajax_success );

	// Remove PLL post handler on ajaxSuccess. It is redundant, achieves nothing,
	// creates redundant secondary requests, and breaks all plugins but Yoast SEO.
	\wp_add_inline_script( 'pll_post', $remove_ajax_success );
}
```

It simply removes the `ajaxSuccess` callback from Polylang's code. That's all that was necessary. No intended behavior in Polylang changes. 
If they ever decide to fix this in Polylang, PR https://github.com/polylang/polylang/pull/943 can be reverted.
